// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            id = new Guid("c298baa3-a5e0-4d5e-8f97-2cec6b98fc12"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2021, 11, 18, 14, 41, 43, 377, DateTimeKind.Local).AddTicks(6062),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            id = new Guid("775e1d6b-377c-41c8-a948-8b1bf0dc797f"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2021, 12, 18, 14, 41, 43, 377, DateTimeKind.Local).AddTicks(6125),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            id = new Guid("825aaf40-38bc-494b-a22e-fa357468c172"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2022, 2, 18, 14, 41, 43, 377, DateTimeKind.Local).AddTicks(6132),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            id = new Guid("43f11f17-6604-43fd-b616-2561f43241b6"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2022, 3, 18, 14, 41, 43, 377, DateTimeKind.Local).AddTicks(6139),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            id = new Guid("0bdf0f3f-affe-4bb7-8b87-51ff2265db70"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 4, 18, 14, 41, 43, 377, DateTimeKind.Local).AddTicks(6145),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            id = new Guid("f5fd9287-e94a-43da-b775-17a0ab3da575"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 5, 18, 14, 41, 43, 377, DateTimeKind.Local).AddTicks(6151),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            id = new Guid("7b84a4d8-b64e-4c29-80d3-f4f0f45fcaf6"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 6, 18, 14, 41, 43, 377, DateTimeKind.Local).AddTicks(6157),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            id = new Guid("caf9e8dd-97ee-41b5-8590-7eb5cc4fcaab"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2022, 7, 18, 14, 41, 43, 377, DateTimeKind.Local).AddTicks(6163),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            id = new Guid("6ba56bd1-a02a-46f3-966f-70f963151141"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2022, 8, 18, 14, 41, 43, 377, DateTimeKind.Local).AddTicks(6174),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            id = new Guid("820504b8-75a0-488e-b15d-4a48878d5c9e"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2022, 9, 18, 14, 41, 43, 377, DateTimeKind.Local).AddTicks(6180),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
